# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14joiNwmFua3uFAILtd50v0EXYlE6dgYS
"""

import tensorflow as tf
import numpy as np
import os
import math
import time

# --- 1. Load Data ---
path_to_file = 'input.txt'  # Make sure this matches your uploaded file name

try:
    text = open(path_to_file, 'rb').read().decode(encoding='utf-8')
    print(f"Length of text: {len(text)} characters")
except FileNotFoundError:
    print("ERROR: File not found. Please upload 'input.txt' to the Files sidebar.")
    raise

# Create vocabulary
vocab = sorted(set(text))
char2idx = {u: i for i, u in enumerate(vocab)}
idx2char = np.array(vocab)
text_as_int = np.array([char2idx[c] for c in text])

# --- 2. Create Dataset ---
seq_length = 100
examples_per_epoch = len(text) // (seq_length + 1)
char_dataset = tf.data.Dataset.from_tensor_slices(text_as_int)

sequences = char_dataset.batch(seq_length + 1, drop_remainder=True)

def split_input_target(chunk):
    input_text = chunk[:-1]
    target_text = chunk[1:]
    return input_text, target_text

dataset = sequences.map(split_input_target)

BATCH_SIZE = 64
BUFFER_SIZE = 10000
dataset = dataset.shuffle(BUFFER_SIZE).batch(BATCH_SIZE, drop_remainder=True)

# --- 3. Build Model (Keras 3 Compatible) ---
vocab_size = len(vocab)
embedding_dim = 256
rnn_units = 1024

def build_model(vocab_size, embedding_dim, rnn_units, batch_size):
    model = tf.keras.Sequential([
        tf.keras.layers.InputLayer(batch_input_shape=[batch_size, None]),
        tf.keras.layers.Embedding(vocab_size, embedding_dim),
        tf.keras.layers.GRU(rnn_units,
                            return_sequences=True,
                            stateful=True,
                            recurrent_initializer='glorot_uniform'),
        tf.keras.layers.Dense(vocab_size)
    ])
    return model

model = build_model(vocab_size, embedding_dim, rnn_units, BATCH_SIZE)

def loss(labels, logits):
    return tf.keras.losses.sparse_categorical_crossentropy(labels, logits, from_logits=True)

model.compile(optimizer='adam', loss=loss)

# --- 4. Train ---
checkpoint_dir = './training_checkpoints'
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt_{epoch}.weights.h5")

checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_prefix,
    save_weights_only=True)

EPOCHS = 20  # You can do more epochs on Colab easily!
print(f"Starting training for {EPOCHS} epochs...")
start_time = time.time()

history = model.fit(dataset, epochs=EPOCHS, callbacks=[checkpoint_callback])

print(f"Training took: {(time.time() - start_time)/60:.2f} minutes")

# Save final weights
model.save_weights("shakespeare_weights.weights.h5")
print("Weights saved successfully.")

# --- 5. Metrics (Perplexity) ---
final_loss = history.history['loss'][-1]
perplexity = math.exp(final_loss)
print(f"\nFinal Loss: {final_loss:.4f}")
print(f"Perplexity: {perplexity:.4f}")

# --- 6. Generate Text ---
print("\nGenerating text...")
model = build_model(vocab_size, embedding_dim, rnn_units, batch_size=1)
model.load_weights("shakespeare_weights.weights.h5")
model.build(tf.TensorShape([1, None]))

def generate_text(model, start_string):
    num_generate = 1000
    input_eval = [char2idx[s] for s in start_string]
    input_eval = tf.expand_dims(input_eval, 0)
    text_generated = []
    temperature = 1.0

    # Access the GRU layer (index 1) to reset its states
    model.layers[1].reset_states() # Changed index from 2 to 1
    for i in range(num_generate):
        predictions = model(input_eval)
        predictions = tf.squeeze(predictions, 0)
        predictions = predictions / temperature
        predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()
        input_eval = tf.expand_dims([predicted_id], 0)
        text_generated.append(idx2char[predicted_id])

    return (start_string + ''.join(text_generated))

print(generate_text(model, start_string=u"ROMEO: "))